# Generated by Django 4.2 on 2026-04-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_masterorder_alter_order_cancelled_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vendor',
        ),
    ]
