# Generated by Django 4.2 on 2026-04-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_customer_remove_order_product_and_more'),
        ('vendors', '0004_alter_vendorreview_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
