# Generated by Django 4.2 on 2026-04-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payout_date_order_payout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, choices=[('nepal_express', 'Nepal Express Courier'), ('fasttrack', 'FastTrack Logistics'), ('himalayan_post', 'Himalayan Post'), ('everest_delivery', 'Everest Delivery'), ('kathmandu_courier', 'Kathmandu Courier Service')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
