# Generated by Django 4.2 on 2026-04-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_items',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='productreview',
            table='product_reviews',
        ),
        migrations.AlterModelTable(
            name='wishlistitem',
            table='wishlist_items',
        ),
    ]
