# Generated by Django 4.2 on 2026-04-18 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_product_category_new'),
    ]

    operations = [
        # Database is already in the final state due to a partially applied previous migration.
        # This migration serves only to align Django's state with the existing database schema.
        migrations.RemoveField(
            model_name='product',
            name='category_new',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
    ]
