# Generated by Django 4.2 on 2026-03-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSignup', '0007_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
