# Generated by Django 4.2 on 2026-03-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSignup', '0011_alter_cartitem_unique_together_cartitem_size_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('running', 'Running'), ('basketball', 'Basketball'), ('football', 'Football'), ('tennis', 'Tennis'), ('swimming', 'Swimming'), ('cycling', 'Cycling')], default='football', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('customer', 'product')},
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
    ]
