# Generated by Django 4.2 on 2026-03-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSignup', '0012_alter_productreview_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('running', 'Running'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('swimming', 'Swimming'), ('cycling', 'Cycling'), ('football', 'Football')], default='football', max_length=50),
        ),
    ]
