# Generated by Django 4.2 on 2026-03-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSignup', '0018_remove_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='admin_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
