# Generated by Django 4.2 on 2026-03-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSignup', '0020_order_esewa_ref_id_order_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
