# Generated by Django 4.2 on 2026-04-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_last_payout_date_vendor_paid_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendor',
            table='vendors',
        ),
        migrations.AlterModelTable(
            name='vendorreview',
            table='vendor_reviews',
        ),
    ]
