# Generated by Django 4.2 on 2026-04-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_customer_remove_order_product_and_more'),
        ('vendors', '0003_alter_vendor_table_alter_vendorreview_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorreview',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_review', to='orders.orderitem'),
        ),
    ]
